networks:
  default:
    name: photos-net
  proxy-net:
    external: true

volumes:
  immich-model-cache:
  immich-postgres-data:

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.138.1
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/tank/photos:/mnt/media/originals:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.http.routers.immich-server.entryPoints: websecure
      glance.category: media
      glance.icon: di:immich
      glance.name: Immich
      glance.url: https://photos.home.hpfr.ch/
      glance.description: Self-hosted photo and video backup solution
      glance.id: immich
    networks:
      - default
      - proxy-net
    env_file: .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.138.1
    ports:
      - 3003:3003
    volumes:
      - immich-model-cache:/cache
    env_file: .env
    labels:
      glance.parent: immich
      glance.name: Machine Learning Agent
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich-redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    env_file: .env
    labels:
      glance.parent: immich
      glance.name: Redis
    restart: always

  database:
    container_name: immich-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - immich-postgres-data:/var/lib/postgresql/data
    labels:
      glance.parent: immich
      glance.name: Database
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=vectors.so",
        "-c",
        'search_path="$$user", public, vectors',
        "-c",
        "logging_collector=on",
        "-c",
        "max_wal_size=2GB",
        "-c",
        "shared_buffers=512MB",
        "-c",
        "wal_compression=on",
      ]
    restart: unless-stopped
