networks:
  default:
    name: smarthome-net
  proxy-net:
    external: true

volumes:
  zigbee2mqtt-data:
  mosquitto-data:


services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.41.0
    container_name: zigbee2mqtt
    restart: unless-stopped
    volumes:
      - zigbee2mqtt-data:/app/data
      - ./config/zigbee2mqtt/configuration.yaml:/app/data/configuration.yaml
      - /run/udev:/run/udev:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.entryPoints=websecure"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8124"
    networks:
      - default
      - proxy-net
    environment:
      - TZ=Europe/Zurich
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2450167-if00:/dev/ttyACM0
    group_add:
      - dialout
    user: 1000:1000

  mqtt:
    image: eclipse-mosquitto:2.0.20
    container_name: mqtt
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - default
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - /var/tmp/docker-storage/mosquitto-logs:/mosquitto/log
    user: 1000:1000

  mqtt-exporter:
    image: kpetrem/mqtt-exporter:1.4.7
    container_name: mqtt-exporter
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - MQTT_ADDRESS=mqtt
      - PROMETHEUS_PREFIX=sensor_
      - TOPIC_LABEL=sensor
    user: 1000:1000
