networks:
  proxy-net:
    external: true

volumes:
  crowdsec-data:
  pocketid-data:

services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.11
    container_name: crowdsec
    restart: unless-stopped
    environment:
      PID: "${PID-1000}"
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/sshd crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/base-http-scenarios"
    volumes:
      - ./config:/etc/crowdsec
      - crowdsec-data:/var/lib/crowdsec/data
      - /etc/localtime:/etc/localtime:ro
      - /var/log/kern.log:/logs/kern.log:ro
      - /var/log/auth.log:/logs/auth.log:ro
      - /var/log/ufw.log:/logs/ufw.log:ro
      - /var/log/syslog:/logs/syslog:ro
      - /var/log/traefik:/logs/traefik:ro
    labels:
      glance.category: monitoring-security
      glance.icon: di:crowdsec
      glance.name: CrowdSec
      glance.description: Open-source security automation platform
      glance.url: https://app.crowdsec.net/security-engines
      glance.id: crowdsec
    security_opt:
      - no-new-privileges=true
    user: 1000:1000
    networks:
      - proxy-net
    ports:
      - 127.0.0.1:8888:8080

  bouncer-traefik:
    image: fbonalair/traefik-crowdsec-bouncer:0.5
    container_name: crowdsec-bouncer-traefik
    restart: unless-stopped
    environment:
      CROWDSEC_BOUNCER_API_KEY: ${TRAEFIK_BOUNCER_KEY}
      CROWDSEC_AGENT_HOST: crowdsec:8080
      GIN_MODE: release
    labels:
      glance.parent: crowdsec
      glance.name: Traefik Bouncer
    depends_on:
      - crowdsec
    networks:
      - proxy-net
    hostname: crowdsec-bouncer-traefik

  pocketid:
    image: ghcr.io/pocket-id/pocket-id:v1.7.0
    container_name: pocketid
    restart: unless-stopped
    environment:
      APP_URL: "https://${DNS_CNAME_POCKETID}"
      PGID: "${GID-1000}"
      PUID: "${PID-1000}"
      TRUST_PROXY: true
      ENCRYPTION_KEY: ${POCKETID_ENCRYPTION_KEY}
      MAXMIND_LICENSE_KEY: ${POCKETID_MAXMIND_LICENSE_KEY}
    labels:
      traefik.enable: true
      traefik.http.routers.pocketid.entrypoints: websecure
      traefik.http.routers.pocketid.rule: Host(`${DNS_CNAME_POCKETID}`)
      glance.category: monitoring-security
      glance.icon: di:pocket-id-light
      glance.name: Pocket ID
      glance.url: https://${DNS_CNAME_POCKETID}/
      glance.description: Open-source identity and access management solution
    volumes:
      - pocketid-data:/app/data
    read_only: true
    user: "1000:1000"
    networks:
      - proxy-net
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3.6.2
    container_name: tinyauth
    restart: unless-stopped
    environment:
      - SECRET=${TINYAUTH_SECRET}
      - APP_URL=https://${DNS_CNAME_TINYAUTH}
      - COOKIE_SECURE=true
      - DISABLE_CONTINUE=true
      - OAUTH_AUTO_REDIRECT=generic
      - GENERIC_CLIENT_ID=${TINYAUTH_POCKETID_CLIENT_ID}
      - GENERIC_CLIENT_SECRET=${TINYAUTH_POCKETID_CLIENT_SECRET}
      - GENERIC_AUTH_URL=https://auth.hpfr.ch/authorize
      - GENERIC_TOKEN_URL=https://auth.hpfr.ch/api/oidc/token
      - GENERIC_USER_URL=https://auth.hpfr.ch/api/oidc/userinfo
      - GENERIC_SCOPES=openid email profile groups
      - GENERIC_NAME=Pocket ID
    labels:
      traefik.enable: true
      traefik.http.routers.tinyauth.entrypoints: websecure
      traefik.http.routers.tinyauth.rule: Host(`${DNS_CNAME_TINYAUTH}`)
      traefik.http.middlewares.tinyauth.forwardauth.address: http://tinyauth:3000/api/auth/traefik
      glance.category: monitoring-security
      glance.icon: di:authentik
      glance.name: TinyAuth
      glance.url: https://${DNS_CNAME_TINYAUTH}/
      glance.description: Lightweight authentication service for Traefik
    networks:
      - proxy-net
