networks:
  proxy-net:
    external: true

volumes:
  crowdsec-data:


services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.5
    container_name: crowdsec
    restart: unless-stopped
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/sshd crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/base-http-scenarios"
    volumes:
      - ./config:/etc/crowdsec
      - crowdsec-data:/var/lib/crowdsec/data
      - /etc/localtime:/etc/localtime:ro
      - /var/log/kern.log:/logs/kern.log:ro
      - /var/log/auth.log:/logs/auth.log:ro
      - /var/log/ufw.log:/logs/ufw.log:ro
      - /var/log/syslog:/logs/syslog:ro
      - /var/log/traefik:/logs/traefik:ro
    security_opt:
      - no-new-privileges=true
    networks:
      - proxy-net
    ports:
      - 127.0.0.1:8888:8080

  bouncer-traefik:
    image: fbonalair/traefik-crowdsec-bouncer:0.5
    container_name: crowdsec-bouncer-traefik
    restart: unless-stopped
    environment:
      CROWDSEC_BOUNCER_API_KEY: ${TRAEFIK_BOUNCER_KEY}
      CROWDSEC_AGENT_HOST: crowdsec:8080
      GIN_MODE: release
    depends_on:
      - crowdsec
    networks:
      - proxy-net
    hostname: crowdsec-bouncer-traefik
