---
networks:
  default:
    name: monitoring-net
  proxy-net:
    external: true
  tools-net:
    external: true
  smarthome-net:
    external: true

volumes:
  vmagent-data:
  victoriametrics-data:
  grafana-data:


services:
  vmagent:
    image: victoriametrics/vmagent:v1.126.0
    container_name: vmagent
    restart: unless-stopped
    volumes:
      - vmagent-data:/vmagentdata
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      glance.category: monitoring-security
      glance.icon: di:prometheus
      glance.name: VictoriaMetrics Agent
      glance.description: Lightweight Prometheus agent for scraping and forwarding metrics
    depends_on:
      - victoriametrics
    ports:
      - 8429:8429
    networks:
      - default
      - proxy-net
      - tools-net
      - smarthome-net
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.127.0
    restart: unless-stopped
    volumes:
      - victoriametrics-data:/storage
    labels:
      glance.category: monitoring-security
      glance.icon: di:prometheus
      glance.name: VictoriaMetrics
      glance.description: High-performance time series database for metrics
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
    networks:
      - default

  grafana:
    image: grafana/grafana-oss:12.1.1
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: "grafana-polystat-panel"
      GF_SERVER_ROOT_URL: "https://grafana.home.hpfr.ch"
      GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP: true
      GF_AUTH_OAUTH_AUTO_LOGIN: true
      GF_AUTH_DISABLE_LOGIN_FORM: true
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.entrypoints: websecure
      glance.category: monitoring-security
      glance.icon: di:grafana
      glance.name: Grafana
      glance.url: https://grafana.home.hpfr.ch/
      glance.description: Open-source platform for monitoring and observability
    hostname: grafana
    networks:
      - proxy-net
      - default
    user: 1000:1000
