api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "schaermu+acme@pm.me"
      storage: "/etc/traefik/acme_letsencrypt.json"
      dnschallenge:
        provider: cloudflare

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
         entryPoint:
           to: "websecure"
           scheme: "https"

  websecure:
    address: ":443"
    http:
      tls:
         certResolver: letsencrypt
         domains:
           - main: hpfr.ch
             sans:
               - "*.hpfr.ch"
               - "*.home.hpfr.ch"
           - main: schaermu.ch
             sans:
               - "*.schaermu.ch"
      middlewares:
        - default@file

global:
  checknewversion: true
  sendanonymoususage: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "proxy-net"
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\" }}.home.hpfr.ch`)"
  file:
    filename: "/etc/traefik/dynamic.conf.yml"
    watch: true
  providersThrottleDuration: 10

log:
  level: "WARNING"
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

metrics:
  prometheus: {}
