networks:
  default:
    name: streaming-net
  download-net:
    external: true
  proxy-net:
    external: true

volumes:
  jellyfin-data:
  tdarr-data:
  navidrome-data:

services:
  jellyfin:
    image: linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      JELLYFIN_PublishedServerUrl: 192.168.1.11
      JELLYFIN_CACHE_DIR: /cache
      JELLYFIN_LOG_DIR: /log
    volumes:
      - jellyfin-data:/config
      - /var/tmp/docker-storage/jellyfin-cache:/cache
      - /var/tmp/docker-storage/jellyfin-logs:/log
      - /mnt/media/video/Serien:/data/tvshows
      - /mnt/media/video/Movies:/data/movies
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.entryPoints: websecure
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      glance.category: media
      glance.icon: di:jellyfin
      glance.name: Jellyfin
      glance.url: https://jellyfin.home.hpfr.ch/
      glance.description: Media server for movies & TV
    hostname: jellyfin
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
    networks:
      - default
      - proxy-net

  navidrome:
    image: deluan/navidrome:0.58.0
    container_name: navidrome
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.navidrome-http.entrypoints: websecure
      glance.category: media
      glance.icon: di:navidrome
      glance.name: Navidrome
      glance.url: https://navidrome.home.hpfr.ch/
      glance.description: Music server for your collection
    hostname: navidrome
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_BASEURL: 
    volumes:
      - navidrome-data:/data
      - /mnt/media/music:/music:ro
    networks:
      - proxy-net
      - default

  lidarr:
    image: linuxserver/lidarr:1.1.4.3027-ls119
    container_name: lidarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
    volumes:
      - ./config/lidarr:/config
      - /mnt/media/music/:/music
      - /mnt/media/downloads:/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.middlewares: tinyauth
      traefik.http.routers.lidarr.entryPoints: websecure
      glance.category: media
      glance.icon: di:lidarr
      glance.name: Lidarr
      glance.url: https://lidarr.home.hpfr.ch/
      glance.description: Music collection manager
    hostname: lidarr
    networks:
      - download-net
      - proxy-net
      - default

  sonarr:
    image: linuxserver/sonarr:4.0.15
    container_name: sonarr
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.middlewares: tinyauth
      traefik.http.routers.sonarr.entryPoints: websecure
      glance.category: media
      glance.icon: di:sonarr
      glance.name: Sonarr
      glance.url: https://sonarr.home.hpfr.ch/
      glance.description: TV series collection manager
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      SONARR__AUTH__METHOD: External
    volumes:
      - ./config/sonarr:/config
      - /mnt/media/video/Serien:/tvshows
      - /mnt/media/downloads:/downloads
    hostname: sonarr
    networks:
      - download-net
      - proxy-net
      - default

  radarr:
    image: linuxserver/radarr:5.27.5
    container_name: radarr
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.middlewares: tinyauth
      traefik.http.routers.radarr.entryPoints: websecure
      glance.category: media
      glance.icon: di:radarr
      glance.name: Radarr
      glance.url: https://radarr.home.hpfr.ch/
      glance.description: Movie collection manager
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      RADARR__AUTH__METHOD: External
    volumes:
      - ./config/radarr:/config
      - /mnt/media/video/Movies:/movies
      - /mnt/media/downloads:/downloads
    hostname: radarr
    networks:
      - download-net
      - proxy-net
      - default

  bazarr:
    image: linuxserver/bazarr:1.5.3
    container_name: bazarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
    volumes:
      - ./config/bazarr:/config
      - /mnt/media/video/Serien:/tvshows
      - /mnt/media/video/Movies:/movies
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.middlewares: tinyauth
      traefik.http.routers.bazarr.entryPoints: websecure
      glance.category: media
      glance.name: Bazarr
      glance.icon: auto-invert di:bazarr
      glance.url: https://bazarr.home.hpfr.ch/
      glance.description: Subtitle management tool
    hostname: bazarr
    networks:
      - default
      - proxy-net

  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    restart: unless-stopped
    volumes:
      - ./config/cleanuparr:/config
    environment:
      PORT: 11011
      BASE_PATH: 
      PUID: 1000
      PGID: 1000
      UMASK: "022"
      TZ: Europe/Zurich
    labels:
      traefik.enable: true
      traefik.http.routers.cleanuparr.middlewares: tinyauth
      traefik.http.routers.cleanuparr.entryPoints: websecure
      traefik.http.services.cleanuparr.loadbalancer.server.port: 11011
      glance.category: media
      glance.icon: di:cleanuperr
      glance.name: CleanupArr
      glance.url: https://cleanuparr.home.hpfr.ch/
      glance.description: Cleanup tool for media managers
    hostname: cleanuparr
    networks:
      - default
      - proxy-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11011/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      UMASK_SET: 002
      internalNode: true
      inContainer: true
      ffmpegVersion: 7
      nodeName: internal-node
      openBrowser: false
      maxLogSizeMB: 10
      cronPluginUpdate: 
      transcodecpuWorkers: 0
      transcodegpuWorkers: 2
      healthcheckgpuWorkers: 0
      healthcheckcpuWorkers: 2
    labels:
      traefik.enable: true
      traefik.http.routers.tdarr.middlewares: tinyauth
      traefik.http.routers.tdarr.entryPoints: websecure
      traefik.http.services.tdarr.loadbalancer.server.port: 8265
      glance.category: media
      glance.icon: di:tdarr
      glance.name: Tdarr
      glance.url: https://tdarr.home.hpfr.ch/
      glance.description: Media transcoding tool
    volumes:
      - ./config/tdarr:/app/configs
      - tdarr-data:/app/server
      - /var/log/tdarr:/app/logs
      - /mnt/media/video:/media
      - /tmp/transcode_cache:/temp
    devices:
      - /dev/dri:/dev/dri
    networks:
      - default
      - proxy-net
  
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      UMASK_SET: 002
      nodeName: docker-node
      serverIP: localhost
      inContainer: true
      ffmpegVersion: 7
      nodeType: mapped
      priority: -1
      cronPluginUpdate: 
      apiKey: 
      maxLogSizeMB: 10
      pollInterval: 2000
      startPaused: false
      transcodegpuWorkers: 2
      transcodecpuWorkers: 0
      healthcheckgpuWorkers: 0
      healthcheckcpuWorkers: 0
    volumes:
      - ./config/tdarr:/app/configs
      - tdarr-data:/app/server
      - /var/log/tdarr:/app/logs
      - /mnt/media/video:/media
      - /tmp/transcode_cache:/temp
    devices:
      - /dev/dri:/dev/dri

  jackett:
    image: linuxserver/jackett:0.24.141
    container_name: jackett
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Zurich
      AUTO_UPDATE: true
    volumes:
      - ./config/jackett:/config
    labels:
      traefik.enable: true
      traefik.http.routers.jackett.middlewares: tinyauth
      traefik.http.routers.jackett.entryPoints: websecure
      glance.category: media
      glance.icon: di:jackett-light
      glance.name: Jackett
      glance.url: https://jackett.home.hpfr.ch/
      glance.description: Proxy for torrent indexers
    hostname: jackett
    networks:
      - default
      - proxy-net

  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.3
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      LOG_LEVEL: debug
      TZ: Europe/Zurich
    volumes:
      - ./config/jellyseerr:/app/config
    labels:
      traefik.enable: true
      traefik.http.routers.jellyseerr-http.entrypoints: websecure
      glance.category: media
      glance.icon: di:jellyseerr
      glance.name: Jellyseerr
      glance.url: https://jellyseerr.home.hpfr.ch/
      glance.description: Request tool for Jellyfin
    hostname: jellyseerr
    networks:
      - default
      - proxy-net
    depends_on:
      - radarr
      - sonarr
      - jellyfin
