networks:
  default:
    name: streaming-net
  download-net:
    external: true
  proxy-net:
    external: true

volumes:
  jellyfin-data:
  navidrome-data:


services:
  jellyfin:
    image: linuxserver/jellyfin:10.10.4
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - JELLYFIN_PublishedServerUrl=192.168.1.11
      - JELLYFIN_CACHE_DIR=/cache
      - JELLYFIN_LOG_DIR=/log
    volumes:
      - jellyfin-data:/config
      - /var/tmp/docker-storage/jellyfin-cache:/cache
      - /var/tmp/docker-storage/jellyfin-logs:/log
      - /mnt/media/video/Serien:/data/tvshows
      - /mnt/media/video/Movies:/data/movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entryPoints=websecure"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    hostname: jellyfin
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
    networks:
      - default
      - proxy-net

  navidrome:
    image: deluan/navidrome:0.54.4
    container_name: navidrome
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome-http.entrypoints=websecure"
    ports:
      - "4533:4533"
    hostname: navidrome
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_BASEURL=
    volumes:
      - navidrome-data:/data
      - /mnt/media/music:/music:ro
    networks:
      - proxy-net
      - default

  lidarr:
    image: linuxserver/lidarr:1.1.4.3027-ls119
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./config/lidarr:/config
      - /mnt/media/music/:/music
      - /mnt/media/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.entryPoints=websecure"
    hostname: lidarr
    ports:
      - 8686:8686
    networks:
      - download-net
      - proxy-net
      - default

  sonarr:
    image: linuxserver/sonarr:4.0.12
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./config/sonarr:/config
      - /mnt/media/video/Serien:/tvshows
      - /mnt/media/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entryPoints=websecure"
    hostname: sonarr
    ports:
      - 8989:8989
    networks:
      - download-net
      - proxy-net
      - default

  radarr:
    image: linuxserver/radarr:5.17.2
    container_name: radarr
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entryPoints=websecure"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./config/radarr:/config
      - /mnt/media/video/Movies:/movies
      - /mnt/media/downloads:/downloads
    hostname: radarr
    ports:
      - 7878:7878
    networks:
      - download-net
      - proxy-net
      - default

  bazarr:
    image: linuxserver/bazarr:1.5.1
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./config/bazarr:/config
      - /mnt/media/video/Serien:/tvshows
      - /mnt/media/video/Movies:/movies
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.entryPoints=websecure"
    hostname: bazarr
    ports:
      - 6767:6767
    networks:
      - default
      - proxy-net

  jackett:
    image: linuxserver/jackett:0.22.1305
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - AUTO_UPDATE=true
    volumes:
      - ./config/jackett:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.entryPoints=websecure"
    hostname: jackett
    ports:
      - 9117:9117
    networks:
      - default
      - proxy-net

  jellyseerr:
    image: fallenbagel/jellyseerr:2.3.0
    container_name: jellyseerr
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr-http.entrypoints=websecure"
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Zurich
    hostname: jellyseerr
    ports:
      - 5055:5055
    networks:
      - default
      - proxy-net
    volumes:
      - ./config/jellyseerr:/app/config
    depends_on:
      - radarr
      - sonarr
      - jellyfin
