- name: Homelab
  columns:
    - size: small
      widgets:
      - type: server-stats
        servers:
        - type: local
          name: fatboy
          hide-swap: true
          hide-mountpoints-by-default: true
          mountpoints:
            "/":
              hide: false
            "/mnt/media":
              hide: false
            "/mnt/external":
              hide: false
      - type: releases
        show-source-icon: true
        collapse-after: 10
        limit: 20
        token: ${GITHUB_TOKEN}
        repositories:
          - jellyfin/jellyfin
          - grafana/grafana
          - VictoriaMetrics/VictoriaMetrics
          - Sonarr/Sonarr
          - Radarr/Radarr
          - Cleanuparr/Cleanuparr
          - deluan/navidrome
          - pi-hole/pi-hole
          - traefik/traefik
          - immich-app/immich
          - pocket-id/pocket-id
          - steveiliop56/tinyauth
          - seanmorley15/AdventureLog
          - linuxserver/docker-transmission
          - crowdsecurity/crowdsec
          - dani-garcia/vaultwarden
          - glanceapp/glance
    - size: full
      widgets:
        - type: split-column
          widgets:
          - type: reddit
            subreddit: selfhosted
            collapse-after: 5
          - type: reddit
            subreddit: homelab
            collapse-after: 5

        - type: docker-containers
          title: Media
          category: media
        - type: split-column
          max-columns: 3
          widgets:
          - type: docker-containers
            title: Download & Network
            category: download-network
          - type: docker-containers
            title: Home Automation
            category: home-automation
          - type: docker-containers
            title: Tools
            category: tools
        - type: docker-containers
          title: Monitoring & Security
          category: monitoring-security
