---
version: "3"
networks:
  default:
    name: torrent-net
  proxy-net:
    external: true

services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.home`)"
      - "traefik.http.routers.transmission.entryPoints=http"
      - "traefik.http.routers.transmission.service=transmission"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config/wireguard-client:/config
      - /lib/modules:/lib/modules
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - default
      - proxy-net
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:version-3.00-r6
    container_name: transmission
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/
    volumes:
      - ./config/transmission:/config
      - /mnt/media/downloads:/downloads
    restart: unless-stopped
