# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.28.0.0/24
    - 127.0.0.1
    - ::1

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

prometheus:
my:
network:
homekit:
  ip_address: 192.168.1.12
  advertise_ip: 192.168.1.12
  
logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug
