---
networks:
  default:
    name: download-net
  proxy-net:
    external: true

services:
  wireguard:
    image: linuxserver/wireguard:1.0.20250521
    container_name: wireguard
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.home.hpfr.ch`)"
      - "traefik.http.routers.transmission.entryPoints=websecure"
      - "traefik.http.routers.transmission.service=transmission"
      - "traefik.http.routers.transmission.middlewares=tinyauth"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./config/wireguard-client:/config
      - /lib/modules:/lib/modules
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - default
      - proxy-net

  transmission:
    image: linuxserver/transmission:4.0.6
    container_name: transmission
    restart: unless-stopped
    network_mode: service:wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - TRANSMISSION_WEB_HOME=/config/flood-for-transmission/
    volumes:
      - ./config/transmission:/config
      - /mnt/media/downloads:/downloads

  sabnzbd:
    image: linuxserver/sabnzbd:4.5.2
    container_name: sabnzbd
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.entryPoints=websecure"
      - "traefik.http.routers.sabnzbd.middlewares=tinyauth"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./config/sabnzbd:/config
      - /mnt/media/downloads:/downloads
      - /mnt/media/downloads/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    networks:
      - default
      - proxy-net
