networks:
  default:
    name: web-net
  proxy-net:
    external: true

services:
  schaermu:
    image: ghcr.io/schaermu/schaermu-ch:2025.5.3
    container_name: schaermu-web
    restart: unless-stopped
    networks:
      - default
      - proxy-net
    labels:
      traefik.enable: true
      traefik.http.routers.schaermu-web.entrypoints: websecure
      traefik.http.routers.schaermu-web.rule: Host(`${DNS_CNAME_SCHAERMU_WEB}`)
      traefik.http.services.schaermu-web.loadbalancer.server.port: 8080
      glance.category: tools
      glance.icon: di:html
      glance.name: schaermu.ch
      glance.url: https://${DNS_CNAME_SCHAERMU_WEB}/
      glance.description: Personal website and blog
